CREATE TABLE enderecos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    logradouro VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    cep VARCHAR(20) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(255) NOT NULL
);
CREATE TABLE medicos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    crm VARCHAR(255) NOT NULL,
        especialidade ENUM('CARDIOLOGIA', 'ORTOPEDIA', 'GINECOLOGIA', 'DERMATOLOGIA'),
    endereco_id BIGINT NOT NULL,
    CONSTRAINT fk_enderecos FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
);

